export const FETCH_CAMPAIGNS = "FETCH_CAMPAIGNS";
export const NEW_CAMPAIGN = "NEW_CAMPAIGN";
export const UPDATE_CAMPAIGN = "UPDATE_CAMPAIGN";
export const GET_CAMPAIGN = "GET_CAMPAIGN";
export const DELETE_CAMPAIGN = "DELETE_CAMPAIGN";
